config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :categories do
    resources :exams
  end
  resources :tests
  resources :randoms, except: [:index]
  resources :test_answers, only: [:index, :update]
  resources :password_resets
  resources :user_activations, only: [:edit, :update]

  get "/home", to: "randoms#index", as: "user_home"
  get "/admin", to: "statics#index"
  get "exams", to: "exams#index"
  get "/users_chart", to: "charts#user_creation_info"
  get "/tests_chart", to: "charts#tests_info"

  get "/upload-exam-file", to: "files#new"
  post "/upload-exam-file", to: "files#upload_exam"
  get "/download_exam_template", to: "files#download_exam_template"

  post "/resend-email", to: "user_activations#create"
  post "/upload-avatar", to: "user_avatars#create"
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: "randoms#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  layout "session"

  before_action :find_user, only: %i(create edit update)
  before_action :check_token_expiration, only: %i(edit)
  before_action :validate_password_confirmation, only: %i(update)

  def new
  end

  def create
    @user.update_attributes reset_token: generate_token, reset_sent_at: Time.zone.now
    UserMailer.reset_password(@user, @user.reset_token).deliver_now

    flash[:success] = "Please check your email for reset instruction"
    redirect_to root_path and return
  end

  def edit
    return if @user.reset_token == params[:id]
    flash[:danger] = "Token mismatch"
    redirect_to root_path and return
  end

  def update
    if @user.update_attributes password: params[:password]
      flash[:success] = "Password reseted"
      redirect_to root_path and return
    else
      flash[:danger] = "Error"
      render :edit
    end
  end

  private

  def find_user
    @user = User.find_by email: params[:email]

    return if @user.present?
    flash.now[:danger] = "Email not exist"
    render :new
  end

  def generate_token
    SecureRandom.urlsafe_base64(nil, false)
  end

  def check_token_expiration
    return unless @user.reset_token_expired?
    flash[:danger] = "Token expired"
    redirect_to root_path and return
  end

  def validate_password_confirmation
    return if params[:password] == params[:password_confirmation]
    flash[:danger] = "Password does not match"
    render :edit
  end
end

app/views/password_resets/edit.html.erb
<div class="sign-in-text">Reset password </div>

<%= render "layouts/flash" %>

<%= form_tag password_reset_path, id: "login-form", method: :patch do %>
  <div class="form-group">
    <%= label_tag :password, "Password" %>
    <%= text_field_tag :password, nil, type: "password", class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= label_tag :password_confirmation, "Password confirmation" %>
    <%= text_field_tag :password_confirmation, nil, type: "password", class: "form-control", required: true %>
  </div>

  <%= hidden_field_tag :email, @user.email %>

  <div class="form-group">
    <%= submit_tag "Reset password", class: "sign-in-btn" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<div class="sign-in-text">Reset password </div>

<%= render "layouts/flash" %>

<%= form_tag password_resets_path, id: "login-form" do %>
  <div class="form-group">
    <%= label_tag :email, "Email" %>
    <%= text_field_tag :email, nil, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= link_to "Back to sign in", new_session_path, class: "forgot-password" %>
  </div>
  <%= submit_tag "Send reset instruction", class: "sign-in-btn" %>
<% end %>