config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :categories do
    resources :exams
  end
  resources :tests
  resources :randoms, except: [:index]
  resources :test_answers, only: [:index, :update]
  resources :password_resets
  resources :user_activations, only: [:edit, :update]

  get "/home", to: "randoms#index", as: "user_home"
  get "/admin", to: "statics#index"
  get "exams", to: "exams#index"
  get "/users_chart", to: "charts#user_creation_info"
  get "/tests_chart", to: "charts#tests_info"

  get "/upload-exam-file", to: "files#new"
  post "/upload-exam-file", to: "files#upload_exam"
  get "/download_exam_template", to: "files#download_exam_template"

  post "/resend-email", to: "user_activations#create"
  post "/upload-avatar", to: "user_avatars#create"
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: "randoms#index"
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  include FileConcern

  before_action :init_exam_file, only: :upload_exam
  before_action :init_file_service, only: :upload_exam
  before_action :check_role

  def new
    @exam_file = ExamFile.new
  end

  def upload_exam
    raise ActiveRecord::RecordInvalid unless @exam_file.valid?
    file_service.create_exam_from_file
    
    if file_service.exam.save!
      redirect_to category_exam_path(params[:category_id], @exam) and return
    end
  rescue ActiveRecord::RecordInvalid
    file_service.exam_file
    render :new
  end

  def download_exam_template
    send_file(
      "#{Rails.root}/public/exam_template.csv",
      filename: "exam_template.csv",
      type: "application/csv"
    )
  end

  private

  attr_reader :exam_file, :exam, :file_service

  def file_valid?
    valid_exam_extension.include? params[:file].content_type.split("/").last
  end

  def init_exam_file
    @exam_file = ExamFile.new name: params[:name], time: params[:time],
      number_of_questions: params[:number_of_questions],
      category_id: params[:category_id], file: params[:file]
  end

  def init_file_service
    @file_service = FileService.new exam_file, params
  end
end

app/views/files/new.html.erb
<div class="exam-show-container import-file-container">
  <h1 class="text-center">Import exam file from excel</h1>
  <%= link_to download_exam_template_path do %>
    <button class="btn2" style="border: none">Download template</button>
  <% end %>

  <% if @exam_file.errors.present? %>
    <div class="error-field">
      <% @exam_file.errors.messages.each do |key, value| %>
        <% value.each do |v| %>
          <div>Error at <%= key.to_s.humanize.downcase %>:&nbsp<%= v.split(".").join(" ") %></div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%= form_tag upload_exam_file_path, multipart: true, method: :post do %>
    <div class="form-group">
      <%= label_tag :category_id, "Category" %>
      <%= select_tag :category_id, options_for_select(Category.all.pluck(:name, :id), selected: @exam_file.category_id), class: "form-control", required: true %>
    </div>

    <div class="form-group <%= "with-error" if @exam_file.errors.messages[:name].present? %>">
      <%= label_tag :name, "Name" %>
      <%= text_field_tag :name, @exam_file.name || nil, class: "form-control", required: true %>
    </div>

    <div class="form-group <%= "with-error" if @exam_file.errors.messages[:name].present? %>">
      <%= label_tag :time, "Time" %>
      <%= number_field_tag :time, @exam_file.time || nil, min: 0, class: "form-control", required: true %>
    </div>

    <div class="form-group <%= "with-error" if @exam_file.errors.messages[:name].present? %>">
      <%= label_tag :number_of_questions, "Number of question when generate test" %>
      <%= number_field_tag :number_of_questions, @exam_file.number_of_questions || nil, min: 0, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <h4>Questions data</h4>
      <label for="file" class="custom-file-upload">Choose file to Upload</label>
      <%= file_field_tag "file", required: true %>
      <span id="file-name-span">No file chosen<span>
    </div>
    <div class="form-group">
      <%= submit_tag "Upload", class: "btn2", id: "upload-exam-csv" %>
    </div>
  <% end %>
</div>