config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :categories do
    resources :exams
  end
  resources :tests
  resources :randoms, except: [:index]
  resources :test_answers, only: [:index, :update]
  resources :password_resets
  resources :user_activations, only: [:edit, :update]

  get "/home", to: "randoms#index", as: "user_home"
  get "/admin", to: "statics#index"
  get "exams", to: "exams#index"
  get "/users_chart", to: "charts#user_creation_info"
  get "/tests_chart", to: "charts#tests_info"

  get "/upload-exam-file", to: "files#new"
  post "/upload-exam-file", to: "files#upload_exam"
  get "/download_exam_template", to: "files#download_exam_template"

  post "/resend-email", to: "user_activations#create"
  post "/upload-avatar", to: "user_avatars#create"
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: "randoms#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exams, -> {order(name: :asc)}, dependent: :nullify
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_role
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find_by id: params[:id]
    @exams = @category.exams
  end
end

app/views/categories/_category.html.erb
<%= link_to  category.name, category_path(category.id) %>

app/views/categories/index.html.erb
<%= render @categories %>

app/views/categories/show.html.erb
<div class="container">
  <br>
  <%#= link_to  "Create new exam", new_category_exam_path(@category.id), class: "btn" %>

  <h1 class="text-center">Exams list of category&nbsp<%= @category.name %></h1>
  <table class="table">
    <tr>
      <th>Exam name</th>
      <th>Number of questions</th>
      <th>Time</th>
      <th>Action</th>
    </tr>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.name %></td>
        <td><%= exam.number_of_questions %></td>
        <td><%= exam.time %></td>
        <td class="action-td">
          <div>
            <%= link_to category_exam_path(@category.id, exam.id), class: "btn" do %>
              <span><%= image_tag "eye.svg", class: "small-icon" %></span>
              <span class="text-in-btn">View</span>
            <% end %>
            <%= link_to "#", class: "btn btn-danger" do %>
              <span><%= image_tag "delete.svg", class: "small-icon" %></span>
              <span class="text-in-btn">Delete</span>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
</div>