config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :categories do
    resources :exams
  end
  resources :tests
  resources :randoms, except: [:index]
  resources :test_answers, only: [:index, :update]
  resources :password_resets
  resources :user_activations, only: [:edit, :update]

  get "/home", to: "randoms#index", as: "user_home"
  get "/admin", to: "statics#index"
  get "exams", to: "exams#index"
  get "/users_chart", to: "charts#user_creation_info"
  get "/tests_chart", to: "charts#tests_info"

  get "/upload-exam-file", to: "files#new"
  post "/upload-exam-file", to: "files#upload_exam"
  get "/download_exam_template", to: "files#download_exam_template"

  post "/resend-email", to: "user_activations#create"
  post "/upload-avatar", to: "user_avatars#create"
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root to: "randoms#index"
end

app/views/layouts/_admin_sidebar.html.erb
<div id="mySidebar" class="sidebar-parent">
  <div class="sidebar2">
    <div class="ul-fake">
      <div class="li-fake">
        <a href="#">
        <%= link_to admin_path do %>
          <div>
            <%= image_tag "organize.svg" %>
            <span class="parent-text-2">Dashboard</span>
          </div>
        <% end %>
      </div>

      <div class="li-fake">
        <%= link_to '#' do %>
          <div>
            <%= image_tag "organize.svg" %>
            <span class="parent-text-2">Exams management</span>
          </div>
          <div class="expandable-2">
          <div>
            <%= link_to upload_exam_file_path do %>
              <div>
                <span>Import from excel</span>
              </div>
            <% end %>
          </div>
          <div>
            <%= link_to new_category_exam_path(Category.first) do %>
              <div>
                <span>Create exam</span>
              </div>
            <% end %>
          </div>
          <div>
            <%= link_to exams_path do %>
              <div>
                <span>All exams</span>
              </div>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>

      <div class="li-fake">
        <a href="#">
          <div>
            <%= image_tag "organize.svg" %>
            <span class="parent-text-2">Test management</span>
          </div>
        </a>
        <div class="expandable-2">
          <div>
            <%= link_to tests_path do %>
              <div>
                <span>All tests</span>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="li-fake">
        <a href="#">
          <div>
            <%= image_tag "organize.svg" %>
            <span class="parent-text-2">Users management</span>
          </div>
        </a>
        <div class="expandable-2">
          <div>
            <%= link_to users_path do %>
              <div>
                <span>All users</span>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %>
    <button type="button" class="btn-alert-close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div id="main">
  <div id="top-bar">
    <ul id="top-bar-ul">
      <li class="bars-icon"><a href="#" id="toggle-nav">&#9776</a></li>
      <li><%= current_user.name %></li>
      <li class="float-right"><%= link_to  "Logout", session_path, method: :delete %></li>
      <li class="float-right ava-header">
        <%= link_to user_path(current_user) do %>
          <% if current_user.avatar.present? %>
            <%= image_tag current_user.avatar_url %>
          <% else %>
            <%= image_tag "/default_avatar.jpg", class: "avatar" %>
          <% end %>
        <% end %>
      </li>
      <li></li>
    </ul>
</div>

app/views/layouts/_popup.html.erb
<div id="popup">
  <%= message %>
</div>

app/views/layouts/_user_sidebar.html.erb
<div id="mySidebar" class="sidebar-parent">
  <div class="sidebar2">
    <div class="ul-fake">
      <div class="li-fake">
        <a href="#">
        <%= link_to '/home' do %>
          <div>
            <%= image_tag "organize.svg" %>
            <span class="parent-text-2">Dashboard</span>
          </div>
        <% end %>
      </div>
      <div class="li-fake">
        <%= link_to user_path(current_user) do %>
          <div>
            <%= image_tag "organize.svg" %>
            <span class="parent-text-2">Profile</span>
          </div>
        <% end %>
      </div>
      <div class="li-fake">
        <a href="#">
          <div>
            <%= image_tag "organize.svg" %>
            <span class="parent-text-2">Test management</span>
          </div>
        </a>
        <div class="expandable-2">
          <div>
            <%= link_to "/home" do %>
              <div>
                <span>Do test</span>
              </div>
            <% end %>
          </div>
          <div>
            <%= link_to tests_path(status: "testing") do %>
              <div>
                <span>Pending test</span>
              </div>
            <% end %>
          </div>
          <div>
            <%= link_to tests_path(status: "tested") do %>
              <div>
                <span>Finished test</span>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RikkeiProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if !current_page?(new_session_path) %>
      <%= render "layouts/header" %>
    <% end %>

    <div id="main-content" data-url="<%= request.base_url %>">
      <%= render "layouts/flash" %>

      <div id="popup-placeholder"></div>

      <%= yield %>
    </div>

    <div>
      <% if current_user.present? %>
        <% if current_user.admin? %>
          <%= render "layouts/admin_sidebar" %>
        <% else %>
          <%= render "layouts/user_sidebar" %>
        <% end %>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RikkeiProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="sign-in-bg">
      <div class="sign-in-container ">

        <%= yield %>
      </div>
    </div>
  </body>
</html>